export const rows = [
    {
        id: 1,
        ID: "1",
        Name: "Mohammed Ebrahim",
        Email: "mohammed.ebrahim9921@gmail.com",
        Age: "26",
        Phone: "(966)570324724",
        Access: "Admin",
    },
    {
        id: 2,
        ID: "2",
        Name: "Cersei Lannister",
        Email: "cerseilannister@gmail.com",
        Age: "42",
        Phone: "(421)314-2288",
        Access: "Admin",
    },
    {
        id: 3,
        ID: "3",
        Name: "Jaime Lannister",
        Email: "jaimelannister@gmail.com",
        Age: "45",
        Phone: "(422)982-6739",
        Access: "Admin",
    },
    {
        id: 4,
        ID: "4",
        Name: "Anya Stark",
        Email: "anyastark@gmail.com",
        Age: "16",
        Phone: "(921)425-6742",
        Access: "Manager",
    },
    {
        id: 5,
        ID: "5",
        Name: "Daenerys Targaryen",
        Email: "daenerystargaryen@gmail.com",
        Age: "31",
        Phone: "(421)445-1189",
        Access: "Manager",
    },
    {
        id: 6,
        ID: "6",
        Name: "Ever Melisandre",
        Email: "evermelisandre@gmail.com",
        Age: "80",
        Phone: "(232)545-6483",
        Access: "User",
    },
    {
        id: 7,
        ID: "7",
        Name: "Ferrara Clifford",
        Email: "ferraraclifford@gmail.com",
        Age: "44",
        Phone: "(543)124-0123",
        Access: "User",
    },
    {
        id: 8,
        ID: "8",
        Name: "Rossini Frances",
        Email: "rossinifrances@gmail.com",
        Age: "36",
        Phone: "(222)444-5555",
        Access: "User",
    },
    {
        id: 9,
        ID: "9",
        Name: "Harvey Roxie",
        Email: "harveyroxie@gmail.com",
        Age: "35",
        Phone: "(444)555-6239",
        Access: "User",
    },
    {
        id: 10,
        ID: "10",
        Name: "Jon Snow",
        Email: "jonsnow@gmail.com",
        Age: "35",
        Phone: "(665)121-5454",
        Access: "User",
    },
];


